version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/coupon_service_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    entrypoint: [ "./.docker/wait-for-it.sh", "db:5432", "--", "sh", "-c", "npx sequelize-cli db:migrate --config sequelize-config.js && npx ts-node src/server.ts" ]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coupon_service_db
    ports:
      - '5433:5432'

  redis:
    image: redis:6
    ports:
      - '6379:6379'